### ISSUE TITLE
Table column with Relation

### ISSUE THREAD

**Issue by kastoras** [singlequote/Laravel-datatables#10]
Hello,

if i have a model that is related with another model, is there any simple way to show related value at datatable column?

Thanks in advance.

**Comment by kastoras** [comment]
Finally i have found a solution, it wasn't hard to do.

I used query method and join the related table.

**Comment by wimurk** [comment]
Hi @kastoras, yes you can use the `query` like below
```php
public function query($query){
   return $query->with('my-relation');
}
```

Or you use the auto detect functionality. In your tableModel you can pass relations in the `$columns` array.

```php
public $columns = [
 'id',
 'my-relation.id' //<== this will be autoloaded
];
```
