### ISSUE TITLE
New Feature, confirm dialog to delete button

### ISSUE THREAD

**Issue by kastoras** [singlequote/Laravel-datatables#11]
Hello, 

i needed to have a confirm dialog when a user click on delete button.

I have made some changes to your source code, i have added onclick method to Button Class.

This way i can send confirm method or js method to handle confirm functionality. 
In my case i use Sweet Alert library to create a confirm dialog.

Example:
At first i have created the js method:
```
function init_confirm_btn(form_id){
    Swal.fire({
        title: 'Διαγραφή;',
        text: 'Είστε σίγουροι ότι θέλετε να προχωρήσετε;',
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Ναι, Διαγραφή!',
        cancelButtonText: 'Άκυρο'
    })
    .then((result) => {
        if (result.value) {
            $('#'+form_id).submit();
        }
    });
}
```

and then i pass it to the button this way

```
Button::make('Ενέργειες')->class('fas fa-times tbl-actions btn btn-icon waves-effect waves-light btn-danger')
->method('delete')
->route('legal-types.destroy', 'id')
 ->onclick('init_confirm_btn(form${id})')
```

If you are interested in this functionality, i can send you the code i have added to your library.

**Comment by wimurk** [comment]
Hi @kastoras. 
It would be a good feature to use `onclicks` on buttons. Can you create a merge request with the code  changes? 

There is a work around for this. When adding the class `preventClick` to the button. The button won't be clickable and you can catch the click with jquery. 
```php
Button::make('Ενέργειες')->class('preventClick fas fa-times tbl-actions btn btn-icon waves-effect waves-light btn-danger')
->method('delete')
->route('legal-types.destroy', 'id')
```

```javascript
$(document).on('click', '.my-button', (e) => {
   //show swal and submit
})
```

**Comment by kastoras** [comment]
Hello @wimurk ,

i didn't notice that i can do this...

i will create a merge request with the functionality, do i need any access to push the code?

**Comment by wimurk** [comment]
@kastoras,

No you can push your code to a new branch.

#12 Add onclick to button field

**Comment by wimurk** [comment]
This issue will now be closed. The changes are visible in the new version
