### ISSUE TITLE
New feature, Add column search

### ISSUE THREAD

**Issue by kastoras** [singlequote/Laravel-datatables#16]
Hello, 

I have made some changes in order to search by column.

If I want the user to be able to search in some columns, I pass one more parameter to table params `'column_search'=>true` for these columns. This creates an input field after the column header title.

Then I am able to use these filters in the query method by accessing them on `$_GET['filter']` parameter like the example below:
```
        if(isset($_GET['filter'])){
            $filtersToArray = json_decode(stripslashes($_GET['filter']));
            if(is_array($filtersToArray)){
                foreach ($filtersToArray as $key => $value) {
                        $query = $query->where($value->filter, 'LIKE', '%'.$value->value.'%');
                }
            }
        }
```
This way, i am able to search in columns.

I can upload the code and working example to check this functionality and add it to the package if it's ok.

**Comment by wimurk** [comment]
@kastoras hi,

Yes you can create a pull request with the changes.

**Comment by wimurk** [comment]
@kastoras in version `3.0.25` you can use the columns search.

**Comment by wimurk** [comment]
The `columnSearch` filters the column a bit diffrent. for example when searching in the users table and you fill in the name `Foo`  the results require to have `Foo` in there column name. 

Set the column search like below
```php
[
            'name' => "name",
            "columnSearch" => true,
            "data" => "name"
 ],
```
