### ISSUE TITLE
Object error for runMiddleware method

### ISSUE THREAD

**Issue by gabyyro** [singlequote/Laravel-datatables#20]
I get following error:

"message": "Argument 1 passed to SingleQuote\\DataTables\\Controllers\\DataTable::runMiddleware() must be an instance of SingleQuote\\DataTables\\Controllers\\object, instance of Illuminate\\Support\\Collection given, called in /path/project/vendor/singlequote/laravel-datatables/src/Controllers/DataTable.php on line 222",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/path/project/vendor/singlequote/laravel-datatables/src/Controllers/DataTable.php",
    "line": 240,

`class Pages extends ColumnBuilder
{

    /**
     * Set the columns for your table
     * These are also your header, searchable and filter columns
     *
     * @var array
     */
    public $columns = [
        'id',
        'slug',
    ];

    /**
     * Alter the fields displayed by the resource.
     *
     * @return array
     */
    public function fields() : array
    {
        return [

        ];
    }
}`

Replacing 
private function runMiddleware(object $collection): object 
with 
private function runMiddleware(\Illuminate\Support\Collection $collection): \Illuminate\Support\Collection
in SingleQuote\DataTables\Controllers\DataTable.php line 240, fixes the issue.

**Comment by wimurk** [comment]
@gabyyro I assume the issue is fixed after you closed it?
