### ISSUE TITLE
Button Route not defined.

### ISSUE THREAD

**Issue by MichaelPanW** [singlequote/Laravel-datatables#21]
According to the example edit the TableModels/Product.php
```bash

    public function fields(): array
    {
        return [
            Button::make('id')->label('edit')->route("product", "id")->method('get')
        ];
    }
```
in web.php
```
Route::get('/product/{id}', function ($id) {
    return 'Product' . $id;
});
```
But System always show
Symfony\Component\Routing\Exception\RouteNotFoundException
Route [product] not defined.

How can i fix it?thx

php:7.2.5
laravel:7.0
laravel-datatables: 3.0

**Comment by wimurk** [comment]
Hi @MichaelPanW you are missing your route name.

```php
Route::get('/product/{id}', function ($id) {
    return 'Product' . $id;
})->name('product'); 
```

**Comment by MichaelPanW** [comment]
Thank you very much ~ Sorry for asking stupid questions

**Comment by wimurk** [comment]
No problem, enjoy the package
