### ISSUE TITLE
Argument 1 passed to SingleQuote\DataTables\Controllers\DataTable::runMiddleware() must be an instance of SingleQuote\DataTables\Controllers\object, instance of Illuminate\Support\Collection given

### ISSUE THREAD

**Issue by ashokdevatwal** [singlequote/Laravel-datatables#24]
Getting Error 

Argument 1 passed to SingleQuote\DataTables\Controllers\DataTable::runMiddleware() must be an instance of SingleQuote\DataTables\Controllers\object, instance of Illuminate\Support\Collection given, called in \vendor\singlequote\laravel-datatables\src\Controllers\DataTable.php on line 227

here what i did 
In My Controller 

    $datatable = \DataTable::model(\App\User::class)->tableModel(\App\TableModels\UsersTable::class);

Datatable Model

UsersTable

    public $columns = [
    'id',        
     'name',
        [
            "data"          => "id",
            "name"          => "id",
            "class"         => "my-class",
            "orderable"     => false,
            "searchable"    => false
        ]
    ];
    public function fields() : array
    {
        return [
            Button::make('id'),
            Label::make('name')
        ];
    }

Thanks.

**Comment by ashokdevatwal** [comment]
related to #20

**Comment by wimurk** [comment]
@ashokdevatwal I assume the issue is fixed for you?
