### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by macgadger** [singlequote/Laravel-datatables#25]
Hi ,

Loved your package :)

while working on it i found that the date there is error in date format. 
Here is the code in fields 

`Date::make('created_at')->format('d M,Y'),`

and the output is 

`08 M, 2021` month is not printing in php format `08 Mar,2021`

and yes is there any way to **add class to Table Header** ?

Could you please look into it.
Thanks.

**Comment by wimurk** [comment]
Hi @macgadger,

Thank you for using our packages. Feel free to contribute new features.
I will dive into the bug asap.

**Comment by macgadger** [comment]
Hi @wimurk 

Solved the bug by  modifiying date.blade.php code:

```
let monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
format = format.replace('M', monthNames[date.getMonth()]);
```

Thanks.

**Comment by wimurk** [comment]
Hi @macgadger glad you solved the issue.

Can you submit a PR so we can fix the bug for everyone?

Thanks
