### ISSUE TITLE
Enhancement: Custom data objects with fields data

### ISSUE THREAD

**Issue by macgadger** [singlequote/Laravel-datatables#28]
Hi @wimurk 

**New enhacement request:**
 while working on data attributes , i found that i can not pass custom strings or route to attributes like:

`Button::make('action')->class('btn btn-outline-info btn-sm modal-link')->icon("fa fa-plus")->data([
                'href'   => 'id',
                'url'     => route('users.edit','id'),
                'placement' => 'top'
   ]),`

with code above i am getting data/errors:

`data-placement="undefined"`in html code
`VM7590:8 Uncaught SyntaxError: Missing } in template expression` in console

Thanks.

**Comment by wimurk** [comment]
Hi @macgadger thats correct, this is still an update in progress.

The feature will be available in the next update
