### ISSUE TITLE
Is it possible to use data for the label on buttons

### ISSUE THREAD

**Issue by happymacarts** [singlequote/Laravel-datatables#35]
I am trying to make a button in my first column I would like the label of the button to be determined by the variable data 

for example
```
Button::make('status.status')
     ->class('btn btn-primary')
     ->route('petitions.show', 'id') // this one is using the 'id' column and works
     ->label('status.status'), // i want this label to pull the column data not show "status.status"
```
would this be a feature request or is there some way to use the data?

**Comment by wimurk** [comment]
The feature is added to #44

**Comment by wimurk** [comment]
You can checkout the docs here [https://singlequote.github.io/Laravel-datatables/fields/button#add-label](https://singlequote.github.io/Laravel-datatables/fields/button#add-label)
