### ISSUE TITLE
Question - How to define default sort column 

### ISSUE THREAD

**Issue by happymacarts** [singlequote/Laravel-datatables#36]
In my datatable i want the default sorted column to not the first column.

in regular datatables you can define 

$('#example').dataTable( {
    "order": [[ 8, 'asc' ]]
} );

how is this accomplished in laravel-datatables?

I know i can return the data pre-sorted but the column icon still shows sorted by column one.

**Comment by wimurk** [comment]
Hi @happymacarts. This is still missing in the docs, but you can sort your columns by adding the `$order` method to your table models like below.

```php
    /**
     * Set order
     *
     * @var mixed
    */
    public $order = [
        [ 2, "desc" ] // sort third column as DESC    
    ];

```
