### ISSUE TITLE
Add functionality for createdRow function

### ISSUE THREAD

**Issue by happymacarts** [singlequote/Laravel-datatables#41]
#37 #40 #39 #38 
enhancement to add functionality for the datatables createdRow Function

**Comment by wimurk** [comment]
Hi @happymacarts, thanks for contributing on the package with new features.

I reviewed your changes and the idea is great and is a nice feature in the package.
As in your code #37 like the docs, you add the script template inside the table model. I think this isn't the right place for the script.

In this case and in the next requests, the package can use the trigger methods like, `on:change,datatable` or `on:done,datatable`. Datatables already uses callbacks like this.

You can use the callbacks in your scripts like this : 

```javascript
$(document).on('datatable:table-rendered', '#myDataTable', (el, row, data) => {
    //table is done rendering
});

$(document).on('datatable:row-rendered', '#myDataTable', (el, row, data) => {
    //row is done rendering
});

$(document).on('datatable:row-clicked', '#myDataTable', (el, row, data) => {
    //row is clicked manual
});

//etc...
```

The packages will need to fire an event everytime something is processed.

**Comment by wimurk** [comment]
The feature is added is the new release. See the docs here
[Triggers](https://singlequote.github.io/Laravel-datatables/table-models#table-triggers)
