### ISSUE TITLE
unable to get colvis button to function using $.fn.dataTable.defaults

### ISSUE THREAD

**Issue by happymacarts** [singlequote/Laravel-datatables#46]
In vs 3.0 they seemed to work fine
but after updating I am unable to get this to work right
```

  $.extend( $.fn.dataTable.defaults, {
        "dom" : '<"datatable"<"btn-toolbar mb-2"B><"d-flex justify-content-between">rt<"d-flex justify-content-between border-top pt-4">>',
        "buttons": [
            'print',            
            {
                  extend: 'csv',
                  text: "Excel",
                  exportOptions: {                      
                      columns: [0, ':visible'],
                  },                  
                  filename: "petitions",
              },
            'copy',
            {
              extend: 'colvis',
              className: 'btn btn-dark',
            }
        ],    	
    })
```

**Comment by wimurk** [comment]
I have tried to add the buttons but on my side it won't work even when adding it directly into the constructor of the $.DataTable config.

What kind of buttons are these?

**Comment by happymacarts** [comment]
$.fn.dataTable.defaults is supposed to allow you to set default parameters for datatable object when options are not declared. but this library is defining most of those properties which is why I found that it will not work this way to leave them undefined. It became easier to just define the properties on my TableModel Object. another noteworthy item is the properties need to be defined in PHP object notation not JSON
```
public $buttons =  [
        [
            'extend' =>  'print',
            'text' => 'Print',
            'exportOptions' => [
                'columns' => [0, ':visible'],
            ],
        ],
        [
            'extend' => 'csv',
            'text' => 'Excel',
            'exportOptions' => [
                'columns' => [0, '=>visible'],
            ],
            'filename' => 'OnlineRequests',
        ],
        'copy',
        [
            'extend' => 'colvis',
            'className' => 'btn btn-dark'
        ]
    ];
```
But to explain these are the default DataTable Buttons Extension https://datatables.net/extensions/buttons/ the above would render like this 
![image](https://user-images.githubusercontent.com/5170850/179814873-888413fc-8956-4270-9a07-f385e4f95029.png)
