### ISSUE TITLE
How to distinguish between column info and text for labels/links et. al?

### ISSUE THREAD

**Issue by happymacarts** [singlequote/Laravel-datatables#51]
I have a user table with a hasMany relation to 'online_requests' which has a hasOne relation to a 'onlineRequestType' which has a name field that i would like to use in the "title" of my link

I am trying to do this 
````
Multiple::make('online_requests')->each('online_requests', function () {
    return [
        Label::make('id')
            ->title("View {onlineRequestType.name}", 'tooltip')
            ->class('ViewORnBtn btn btn-sm btn-info my-1')
            ->data(['id' => 'id']),

    ];
})

public function query($query)
    {
        return $query->with('roles','onlineRequests', 'onlineRequests.onlineRequestType');
    }
````
any suggestions on how to use nested relations in the tooltip?

**Comment by wimurk** [comment]
Hi @happymacarts this isnt possible yet. Might be a good update tho.
